dim_scenario_dianping_poi_ddl = """
        CREATE TABLE IF NOT EXISTS dim_scenario_dianping_poi
        (
            store_id              STRING COMMENT '店铺id',
            store_url             STRING COMMENT '店铺连接',
            store_name            STRING COMMENT '店铺名',
            branch_store          STRING COMMENT '分店',
            branches_cnt          BIGINT COMMENT '分店数量',
            store_status          STRING COMMENT '状态：暂停营业/商户已关闭/商户暂未营业，空为正常',
            business_hours        STRING COMMENT '营业时间',
            province              STRING COMMENT '省',
            city                  STRING COMMENT '市',
            district              STRING COMMENT '区',
            business_district     STRING COMMENT '商圈',
            cate_leve_1           STRING COMMENT '一级类目',
            cate_leve_2           STRING COMMENT '二级类目',
            cate_leve_3           STRING COMMENT '三级类目',
            taste_rating          DOUBLE COMMENT '口味评分',
            environmental_rating  DOUBLE COMMENT '环境评分',
            service_rating        DOUBLE COMMENT '服务评分',
            total_score           DOUBLE COMMENT '总评分',
            average_price         BIGINT COMMENT '人均客单价',
            comment_cnt           BIGINT COMMENT '评价数',
            collect_cnt           DOUBLE COMMENT '收藏数（万人）',
            is_group_purchase     BIGINT COMMENT '是否有团购，1有0无',
            is_discounts          BIGINT COMMENT '是否有优惠，1有0无',
            is_queue              BIGINT COMMENT '是否有排队，1有0无',
            is_pay_order          BIGINT COMMENT '是否有买单，1有0无',
            is_promote            BIGINT COMMENT '是否有促销，1有0无',
            is_takeaway           BIGINT COMMENT '是否有外卖，1有0无',
            is_booking            BIGINT COMMENT '是否有订座，1有0无',
            is_hotel_reservation  BIGINT COMMENT '是否有酒店预约，1有0无',
            is_beauty_reservation BIGINT COMMENT '是否有美容预约，1有0无',
            is_black_pearl        BIGINT COMMENT '是否有黑珍珠，1有0无',
            recommendation        STRING COMMENT '推荐',
            list                  STRING COMMENT '榜单',
            food_awards           STRING COMMENT '入围',
            store_tag             STRING COMMENT '店铺标记',
            store_label           STRING COMMENT '店铺标签',
            images_cnt            BIGINT COMMENT '关联图片数',
            store_image           STRING COMMENT '店铺关联图',
            route                 STRING COMMENT '路线',
            address               STRING COMMENT '地址',
            longitude             STRING COMMENT '经度',
            latitude              STRING COMMENT '维度'
        ) 
"""